added giorgi.tarsaidze.mdx
bitcamp-ge/bitcamp.ge pull request #13
Opened 2023-09-22 20:43 UTC by GiorgiTarsaidze

2023-09-24 12:29 UTC, otarza requested changes
@GiorgiTarsaidze გთხოვ განაახლო კომენტარების შესაბამისად.

2023-09-24 12:29 UTC, otarza commented on content/mentors/giorgi-tarsaidze.mdx
> +<!-- ---
@GiorgiTarsaidze აქ არასწორი სინტაქსი გაქვს გამოყენებული, ასე უნდა იყოს: 

``` 
---
title: გიორგი ტარსაიძე
description: მენტორი, Python პროგრამის ხელმძღვანელი 🔥🐍
---
```

2023-09-24 12:29 UTC, otarza commented on content/mentors/giorgi-tarsaidze.mdx
> +<iframe
iframe - ის გამოყენება არ არის საჭირო. 

შენი სურათი ატვირთე `public/images/mentors/` ფოლდერში და სურათის ჩასასმელად გამოიყენე Markdown - ის სინტაქსი: `![Image caption](/images/mentors/your-image.png)`

2023-09-24 12:51 UTC, GiorgiTarsaidze commented
@otarza

2023-09-26 05:22 UTC, otarza approved these changes

2023-09-26 05:23 UTC, merged