Add nika-kipshidze.mdx
bitcamp-ge/bitcamp.ge pull request #14
Opened 2023-09-23 07:32 UTC by NickKipshidze

## Nick Kipshidze

- Added `nika-kipshidze.mdx` file inside `./content/mentors` directory.

2023-09-24 12:25 UTC, otarza requested changes
@NickKipshidze გთხოვ გადახედო კომენტარებს და განაახლო PR შესაბამისად.

2023-09-24 12:25 UTC, otarza commented on content/mentors/nika-kipshidze.mdx
> +<h1 align="center" style={{ color: "#e2c086", fontSize: "50px" }}>გამარჯობა</h1>
@NickKipshidze markdown - ის სინტაქტი გამოიყენე მხოლოდ. h1, p ტექგები არ არის საჭირო, ასევე ფერების დამატებაც არ იქნება კარგი იდეა, საიტის ძირითად სტილს არ მოუხდება.

2023-09-24 12:25 UTC, otarza commented on content/mentors/nika-kipshidze.mdx
> +<p style={{ color: "#F04464", fontSize: "30px", fontWeight: 900 }}>გჭირდება!</p>
აქაც p ტეგის გამოყენება არ არის საჭირო.

2023-09-24 12:50 UTC, NickKipshidze commented
უკვე TikTok-ის ხანა, რომ არის და average ინტერნეტის მომხმარებელს არ შეუძლია 1 წუთი ყურადღების მიქცევა ერთი რამისთვის, მაგიტომ ვეცადე, რომ ბევრი ფერებით და საინტერესო გაფორმებით მიმექცია ყურადღება. მაგრამ მართალია, საიტის ძირითად სტილს არ უხდება.

2023-09-26 05:20 UTC, otarza approved these changes

2023-09-26 05:20 UTC, merged