levaniakobidze.mdx
bitcamp-ge/bitcamp.ge pull request #15
Opened 2023-09-23 12:29 UTC by levaniakobidze

2023-09-24 12:19 UTC, otarza requested changes
@levaniakobidze გთხოვ გადახედე კომენტარებს და შესაბამისი ცვლილებებით განაახლე PR.

2023-09-24 12:19 UTC, otarza commented on content/mentors/levaniakobidze.mdx
> +```js
@levaniakobidze MDX ფაილები სათაურის და description ველებით უნდა დაიწყოს: 

---
title: სახელი და გვარი
description: მოკლე აღწერა. მაქსიმუმ 4-5 სიტყვა.
---

2023-09-24 12:19 UTC, otarza commented on content/mentors/levaniakobidze.mdx
> +🔽🔽 შეთავაზებები 🔽🔽 ![⬇️](https://discordapp.com/assets/31abf4145cf7c27ea0e1a2e4328283fd.svg)![⬇️](https://discordapp.com/assets/31abf4145cf7c27ea0e1a2e4328283fd.svg)![⬇️](https://discordapp.com/asset
Didcosrd - ის მისამართზე არ უნდა იყოს ეს სურათები. 

public/images/ - ფოლდერში გადმოწერე და რელაციური მისამართები გამოიყენე Markdown - ში `/images/{folder_name}/file_name.svg`

2023-09-24 15:04 UTC, levaniakobidze commented on content/mentors/levaniakobidze.mdx
> +```js
გავასწორე

2023-09-24 15:04 UTC, levaniakobidze commented on content/mentors/levaniakobidze.mdx
> +🔽🔽 შეთავაზებები 🔽🔽 ![⬇️](https://discordapp.com/assets/31abf4145cf7c27ea0e1a2e4328283fd.svg)![⬇️](https://discordapp.com/assets/31abf4145cf7c27ea0e1a2e4328283fd.svg)![⬇️](https://discordapp.com/asset
გავასწორე

2023-09-25 13:08 UTC, otarza approved these changes

2023-09-26 05:19 UTC, otarza approved these changes

2023-09-26 05:19 UTC, merged