add temuri-tsutskiridze.mdx file
bitcamp-ge/bitcamp.ge pull request #6
Opened 2023-09-22 12:22 UTC by TemuriTsutskiridze

2023-09-24 12:52 UTC, otarza requested changes
@TemuriTsutskiridze გთხოვ გადახედე კომენტარებს.

2023-09-24 12:52 UTC, otarza commented on content/mentors/temuri-tsutskiridze.mdx
> +# მოგესალმებით პროგრამირების სამყაროში 🔥✊
@TemuriTsutskiridze ეს სექცია გაქვს გამორჩენილი:
```
---
title: სახელი და გვარი
description: მოკლე აღწერა, მაგალითად "BitCamp - ის მენტორი", ან რაიმე მსგავსი. 
---
```
content ფოლდერში ჩაიხედე ნიმუშებისთვის.

2023-09-24 12:52 UTC, otarza commented on content/mentors/temuri-tsutskiridze.mdx
> +### 👋 სალამი, მეგობრებო, მე ვარ თემურ ცუცქირიძე, 18 წლის, Bitcamp Front-End-ის მენტორი. უკვე ერთი წელია, რაც Front-End დეველოპერი ვარ. სანამ შეთავაზებებზე გადავალ, მოდით ცოტას ჩემზეც მოგიყვებით. ბოლო
სათაურის ფორმატში ამხელა ტექსტის ჩაწერა არ იქნება ლამაზი.

2023-09-24 12:52 UTC, otarza commented on content/mentors/temuri-tsutskiridze.mdx
> +[![Temuri Tsutskiridze Profile Photo](https://i.postimg.cc/Fs6RsfBY/Screenshot-2023-09-20-150133.png)](https://postimg.cc/N51Yd0Yt)
სურათები ატვირთე public/images/mentors/ განყოფილებაში და გამოიყენე რელაციური მისამართებით. წინ public არ დასჭირდება გამოყენებისას, პირდაპირ /images/...

ასევე სურატს უნდა ერქვას კარგი სახელი, Screenshot არ ვარგა. ასევე სჯობს ზოგადად სქრინშოთი არ იყოს და კარგი ხარისხის სურათი გვქონდეს.

2023-09-24 12:52 UTC, otarza commented on content/mentors/temuri-tsutskiridze.mdx
> +### ![💪](https://discord.com/assets/1837c5719a977362642ffaf4990b6bac.svg)ახლა კი შეთავაზებებზე გადავალ, ძაან მაგარ რაღაცებს გიმზადებთ 🔥![🔥](https://discord.com/assets/67069a13e006345ce28ecc581f2ed162
აქაც სურათები ფოლდერში ჩაყარე + სურათების სათაურში გამოყენება არ ვიცი რამდენად კაი იდეაა.

2023-09-24 12:52 UTC, otarza commented on content/mentors/temuri-tsutskiridze.mdx
> +* ორშაბათი - 10:00-23:00&#x20;
`&#x20;` ეს რა სიმბოოლოებია?

2023-09-24 12:52 UTC, otarza commented on content/mentors/temuri-tsutskiridze.mdx
> +#### ასევე, ვიქნები თქვენი ლექტორიც, სილაბუსის მიხედვით ჩაგიტარებთ თეორიულ და პრაქტიკულ ლექციებს Javascript, Front-End Basics და React.js-ის მიმართულებით
აქაც, სათაურის ადგილას ამხელა ტექსტი არმოსულა.

2023-09-24 12:52 UTC, otarza commented on content/mentors/temuri-tsutskiridze.mdx
> +### მოკლედ, ამდენ მაგარ, საინტერესო და მრავალფეროვან შეთავაზებებს ერთად ვერსად ნახავთ, ხოდა რაღას უცდით, ამირჩიეთ მენტორად, შემომიერთდით და ერთად დავიწყოთ სწავლა და ბრძოლა 🔥✊
აქაც, სათაურის ფორმატში ამხელა ტექსტი არმოსულა.

2023-09-24 19:34 UTC, TemuriTsutskiridze commented on content/mentors/temuri-tsutskiridze.mdx
> +# მოგესალმებით პროგრამირების სამყაროში 🔥✊
done

2023-09-24 19:34 UTC, TemuriTsutskiridze commented on content/mentors/temuri-tsutskiridze.mdx
> +### 👋 სალამი, მეგობრებო, მე ვარ თემურ ცუცქირიძე, 18 წლის, Bitcamp Front-End-ის მენტორი. უკვე ერთი წელია, რაც Front-End დეველოპერი ვარ. სანამ შეთავაზებებზე გადავალ, მოდით ცოტას ჩემზეც მოგიყვებით. ბოლო
done

2023-09-24 19:34 UTC, TemuriTsutskiridze commented on content/mentors/temuri-tsutskiridze.mdx
> +[![Temuri Tsutskiridze Profile Photo](https://i.postimg.cc/Fs6RsfBY/Screenshot-2023-09-20-150133.png)](https://postimg.cc/N51Yd0Yt)
done

2023-09-24 19:34 UTC, TemuriTsutskiridze commented on content/mentors/temuri-tsutskiridze.mdx
> +### ![💪](https://discord.com/assets/1837c5719a977362642ffaf4990b6bac.svg)ახლა კი შეთავაზებებზე გადავალ, ძაან მაგარ რაღაცებს გიმზადებთ 🔥![🔥](https://discord.com/assets/67069a13e006345ce28ecc581f2ed162
done

2023-09-24 19:34 UTC, TemuriTsutskiridze commented on content/mentors/temuri-tsutskiridze.mdx
> +* ორშაბათი - 10:00-23:00&#x20;
ამოვშალე, done

2023-09-24 19:34 UTC, TemuriTsutskiridze commented on content/mentors/temuri-tsutskiridze.mdx
> +#### ასევე, ვიქნები თქვენი ლექტორიც, სილაბუსის მიხედვით ჩაგიტარებთ თეორიულ და პრაქტიკულ ლექციებს Javascript, Front-End Basics და React.js-ის მიმართულებით
done

2023-09-24 19:34 UTC, TemuriTsutskiridze commented on content/mentors/temuri-tsutskiridze.mdx
> +### მოკლედ, ამდენ მაგარ, საინტერესო და მრავალფეროვან შეთავაზებებს ერთად ვერსად ნახავთ, ხოდა რაღას უცდით, ამირჩიეთ მენტორად, შემომიერთდით და ერთად დავიწყოთ სწავლა და ბრძოლა 🔥✊
done

2023-09-26 05:26 UTC, otarza approved these changes

2023-09-26 05:26 UTC, merged